### ISSUE TITLE
Color not working

### ISSUE THREAD

**Issue by robotsbecool** [OkiStuff/ConsoleGL#3]
After updating to ConsoleGL 1.0.9 every time I add any color to anything
![Screenshot (97)](https://user-images.githubusercontent.com/65093517/87841893-8b220e00-c85d-11ea-8fd7-e908333df79d.png)
It doesnt show anything (cant post a screenshot because it automatically closes when I open the rb file)

**Comment by OkiStuff** [comment]
Is there any errors?

**Comment by robotsbecool** [comment]
How would I check?

**Comment by OkiStuff** [comment]
It would only show in the command prompt but its find I found the cause of the issue. Thank you so much. 1.0.10 for bug fix and then 1.1 for new features

**Comment by OkiStuff** [comment]
I am pushing the update to ruby gems right now
Thanks so much for the bug report

**Comment by OkiStuff** [comment]
Version 1.0.10 has been pushed to Ruby Gems
