### ISSUE TITLE
How to exit on pressed key

### ISSUE THREAD

**Issue by robotsbecool** [OkiStuff/ConsoleGL#4]
## Question
The title explains it already but I have this code that I want to end once a key is pressed.

**Comment by OkiStuff** [comment]
So you want the app to exit on a key press?

**Comment by robotsbecool** [comment]
yes basically

**Comment by OkiStuff** [comment]
Alright I'll check in that

**Comment by OkiStuff** [comment]
I'll check on it

**Comment by OkiStuff** [comment]
Here
```ruby
require 'ConsoleGL'

# loop
while true do
    if Input.KeyPressed("a")
        puts "CORRECT KEY PRESSED"
        exit
    else
        puts "INCORRECT KEY PRESSED"
    end
end
```

`exit` exits the app. its a part of ruby so no need to update ConsoleGL

**Comment by OkiStuff** [comment]
Tell me if it works
