### ISSUE TITLE
About Wiki

### ISSUE THREAD

**Issue by robotsbecool** [OkiStuff/ConsoleGL#5]
## Question
Color and Input both only have one thing right now on the wiki, is there going to be more like `Input.GetAnyKey` or `Color.LastColor` (idk what color and input should have im just making stuff up)

**Comment by robotsbecool** [comment]
I mean I can think of Input getting new things but not so much for color, maybe the alpha of a color?

**Comment by OkiStuff** [comment]
Those are great ideas. Yes those will be added

**Comment by OkiStuff** [comment]
For the alpha I will have to figure out how to do it
